src/data/near.js, src/vm/vm.js
API server is a dedicated RPC server for providing get/keys actions. The server is fast and should be used for fetching large queries that requires ton of iterations on the data. E.g.
```javascript
const data = Social.keys("*/profile", "final");
```
It also supports historical data fetches starting from block `75942519`.
In the future the APIs can be expanded to support more data operations, e.g. get edit history for a field.
=> Enable API server for non optimistic finality requests

src/vm/vm.js
- Refactor MemberExpression.
- Better error handling on function calls
- Don't JSONIFY props and state.
This enables ability to pass functions as props into other widgets. For example, implement a helper edit widgets like `ImageSelector` that takes the following props:
```jsx
{
image: state.image,
onChange: (image) => State.update({image}),
}
```
It should be able to call `onChange` and the root component should update.
=> Function props

src/App.scss, src/pages/EditorPage.js
- Use Tabs for editor, props and the preview.
- Monaco editor for JSON on props.
- Auto-render on switch to preview
=> Redesign editor to be full width

src/components/Commit.js, src/components/Widget/Widget.js, src/data/cache.js, src/data/utils.js, src/vm/vm.js
A successful commit action will trigger automatic cache invalidation for affected widgets. Those widgets will refetch the data and re-render.
=> Cache invalidation

package.json, src/App.js, src/components/Commit.js, src/components/ConfirmTransaction.js, src/components/Widget/Widget.js, src/data/cache.js, src/data/commitData.js, src/data/near.js, src/pages/EditorPage.js, src/vm/vm.js, yarn.lock
With this cache rework, the page loads much faster, because old values are stored in the cache. This may lead to potential issues if the newly fetched value returns invalid value or fails. The old value maybe not refreshed.
Widgets may use the first available value, which can be non recent. This may result in strange results.
- Rework how fetching works to be fully sync.
- All cached calls require to provide `onInvalidate` callback.
- Move `selector` to async to speed up page load.
=> Save fetched data to local DB. Refresh when new value is fetched

src/data/cache.js, src/vm/vm.js
Add `Social.index` method that calls API server.
Args:
- `action` is the `index_type` from the standard, e.g. in the path `index/like` the action is `like`.
- `key` is the inner indexed value from the standard.
- (optional) `options` an object:
- (optional) `accountId`. If given, it should either be a string or an array of account IDs to filter values by them. Otherwise, not filters by account Id.
Returns the array of matched indexed values. Ordered by `blockHeight`. E.g. 
```json
[
{
"accountId": "mob.near",
"blockHeight": 78672789,
"value": "test-value-1"
},
{
"accountId": "mob.near",
"blockHeight": 78672797,
"value": "test-value-1"
},
{
"accountId": "mob.near",
"blockHeight": 78672974,
"value": "test-value-3"
}
]
```
Examples:
```jsx
return Social.index("test", "test-key-2");
``` …
=> Add Social.index

src/vm/vm.js
Add Tooltip and OverlayTrigger from react-bootstrap.
Shows tooltips.
```jsx
return (
<OverlayTrigger placement="auto" overlay={<Tooltip>I'm tooltip</Tooltip>}>
<button>Test</button>
</OverlayTrigger>
);
```
=> Add Tooltip and OverlayTrigger

src/components/Widget/Widget.js, src/data/near.js
Added `context.loading` for the duration while wallet-selector is loading account data from chain. 
```jsx
const accountId = context.accountId;
if (context.loading) {
return "Loading";
}
if (!accountId) {
return "Please sign in with NEAR wallet to use this widget";
}
return `Hello, ${accountId}!`;
```
=> Add account loading to context

src/App.js, src/components/Widget/Widget.js, src/data/cache.js, src/vm/vm.js
Add `Storage` object to store data for widgets that is persistent across refreshes. Simulates localStorage access. It has 4 methods:
- `Storage.set(key, value)` - sets the public value for a given key under the current widget. The value will be public, so other widgets can read it.
- `Storage.get(key, widgetSrc?)` - returns the public value for a given key under the given widgetSrc or the current widget (if `widgetSrc` is omitted). Can only read public values.
- `Storage.privateSet(key, value)` - sets the private value for a given key under the current widget. The value is private, only the current widget can read it. Private and public values can share the same key and don't conflict.
- `Storage.privateGet(key)` - returns the private value for a given key under the current widget.
```jsx …
```
=> Add Storage object

src/data/cache.js, src/vm/vm.js
Introducing two new methods:
- `Near.asyncView` - returns a promise to a view call. It doesn't cache the value, so it should only be used within a function to avoid frequent requests on every render.
- `asyncFetch` - returns a promise to `fetch` result. It doesn't cache the value, so it should only be used within a function to avoid frequent requests on every render.
Within the main body of a widget code you shouldn't use either method and instead rely on cached non-async methods (`Near.view` and `fetch`). But async code is required when you have to make an async decision, e.g. to chain a few promises together. Since the VM can't easily switch to support `async` functions with `await`, the best option is to rely on promises which are synchronous within blocks. `Promise.all` can be added …
=> Add async methods that return promises

src/components/Commit.js, src/components/Widget/Widget.js, src/data/utils.js, src/vm/vm.js
This PR brings two big changes.
Takes `data` object and commits it to SocialDB. It works similarly to the `CommitButton` by spawning the modal window prompt to save data, but it doesn't have to be triggered through the commit button component. It allows you to write more flexible code that relies on async promises and use other events and components. Overall it enables more flexibility when committing to SocialDB. For example, you can commit when Enter key pressed.
Arguments:
- `data` required, the data object to be committed. Similar to `CommitButton`, it shouldn't start with account ID.
- `options` optional object
- `force`, whether to overwrite the data
- `onCommit` - function to trigger on successful commit. Will pass the data that was written (including accountID)
- `onCancel` - …
=> Social.set and skip confirm toggle

src/components/Sidebar.js
Currently to get to edit route quickly requires hitting new widget, would be nice to just get there when navigating the app.  Calling it workspace for now.
=> feat: update sidebar to get to edit route quickly call it workspace

src/data/cache.js, src/vm/vm.js
All cached VM methods got a new option to subscribe to the query. Currently, it's implemented as a 5 seconds timer, at which the data is refreshed for all subscribers.
Methods that are updated, with examples for subscribing:
- `Near.view(contractName, methodName, viewArg, blockId, subscribe)` needs `subscribe` to be `true`.
- `Near.block(blockId, subscribe)` needs `subscribe` to be `true`.
- `fetch(url, options)`, needs `options.subscribe` to be `true`.
- `Social.get(keys, blockId, options)`, needs `options.subscribe` to be `true`.
- `Social.getr(keys, blockId, options)`, needs `options.subscribe` to be `true`.
- `Social.keys(keys, blockId, options)`, needs `options.subscribe` to be `true`.
- `Social.index(action, key, options)`, needs `options.subscribe` to be `true`.
Example:
```jsx …
```
=> Add subscribe option to VM

src/vm/vm.js
Expose `Map` and `Set` keywords. Add them to deepCopy.
```jsx
const map1 = new Map();
map1.set("a", 1);
map1.set("b", 2);
map1.set("c", 3);
console.log(map1.get("a"));
// expected output: 1
map1.set("a", 97);
console.log(map1.get("a"));
// expected output: 97
console.log(map1.size);
// expected output: 3
map1.delete("b");
console.log(map1.size);
// expected output: 2
const mySet1 = new Set();
mySet1.add(1); // Set(1) { 1 }
mySet1.add(5); // Set(2) { 1, 5 }
mySet1.add(5); // Set(2) { 1, 5 }
mySet1.add("some text"); // Set(3) { 1, 5, 'some text' }
const o = { a: 1, b: 2 };
mySet1.add(o);
mySet1.add({ a: 1, b: 2 }); // o is referencing a different object, so this is okay
mySet1.has(1); // true
mySet1.has(3); // false, since 3 has not been added to the set
mySet1.has(5); // true …
```
=> Add Map and Set objects

src/vm/vm.js
Fixes: #68 
```jsx
const expr = 'Papayas';
switch (expr) {
case 'Oranges':
console.log('Oranges are $0.59 a pound.');
break;
case 'Mangoes':
case 'Papayas':
console.log('Mangoes and papayas are $2.79 a pound.');
// expected output: "Mangoes and papayas are $2.79 a pound."
break;
default:
console.log(`Sorry, we are out of ${expr}.`);
}
```
=> Add SwitchStatement

src/data/commitData.js
Some wallets don't provide a limited access key from wallet selector. In this case we can't request the write permission for the key. The fallback was not attaching the deposit properly.
=> Fix commitData without limited access key

src/components/Editor/OpenModal.js, src/components/Editor/RenameModal.js
Fixes #74
Only allowed characters can now be entered in Open/Rename modals
=> Filter out non-valid characters from Open/Rename modals

package.json, src/components/Markdown.js, src/components/remark/mentions.js
- Introduce mentions to Markdown component.
By default it turns `@mob.near` into bold, but if `onMention` is passed, it calls it with the accountId instead.
Example code:
```jsx
const renderMention =
((accountId) => (
<Widget
src="mob.near/widget/ProfileLine"
props={{ accountId, hideAccountId: true, tooltip: true }}
/>
));
return <Markdown text="Hi @root.near" onMention={renderMention} />;
```
=> Add onMention to Markdown tag that parses Near's account IDs

src/vm/vm.js
Previously Assignment was deleting entries from the original object.
```jsx
const o = {a: 1, b: 2};
const {a} = o;
console.log(o);
```
=> Fix RestElement to not delete entries

src/vm/vm.js
Previously all default JS properties were prohibited. Switches to proper blacklist instead.
```jsx
const a = new Date().toLocaleString();
const b = new Date().toString();
let c = "err";
try {
c = new Date().constructor();
} catch (e) {
c = e.message;
}
return [a, b, c];
```
=> Allow use toLocaleString()

src/vm/vm.js
This reverts commit 81e0a19e1a1d1dbe4b8e7095acff2cd76e7374f5.
Classes have static methods and they are considered functions. There are no benefit of only banning dereferencing of pure functions.
=> Revert "Prevent functions from being dereferenced (#120)"

src/components/Commit.js, src/components/icons/Pretend.js, src/components/icons/StopPretending.js, src/components/navigation/PretendModal.js, src/components/navigation/desktop/DevActionsDropdown.js, src/components/navigation/desktop/UserDropdown.js, src/data/account.js, src/data/commitData.js, src/data/near.js
Adds a button to the desktop menu to act as a different account. If you attempt to commit the data, it will be submitted from your original account, but on behalf of the pretended account. The write permission is required to commit data.
=> Ability to browse and act as a different account

src/components/Widget/Widget.js, src/vm/vm.js
Introduce `config` property on the `Widget` component. It allows you to recursively redirect widgets' `src` to a different `src` or code itself.
The config may contain two properties:
- `redirectMap` (optional) - has to be an object that maps from `src` to `SrcOrCode` value.
- `redirect` (optional) - a function that will be called if `redirectMap` doesn't have `src`. The function receives `src` and should return `SrcOrCode` value or `null` (in case of no redirect).
`SrcOrCode` represents either `src` (string value) or `{ code }` object with key `code` and string value. Examples:
- `"mob.near/widget/TimeAgo"` - the `src`
- `{ code: "return \"No likes for you!\""}` - the code to be passed to the widget instead of the `src`
When child widget specifies `config`, the its config will be …
=> Ability to recursively redirect widget's src

src/components/Widget/Widget.js, src/vm/vm.js
Fixes: #76 
This PR also adds ability to update state by passing a function.
Adds four methods:
- setTimeout
- clearTimeout
- setInterval
- clearInterval
Note, that within `setInterval`, the state is not being updated properly: https://eight-bites.blog/en/2021/05/setinterval-setstate/
```jsx
if (state === undefined) {
State.init({
counter: 0,
});
setInterval(() => {
State.update((state) => ({
...state,
counter: state.counter + 1,
}));
}, 100);
}
return <div>Hello World {state.counter}</div>;
```
=> Add timeout methods

src/vm/vm.js
https://styled-components.com/docs/api#as-polymorphic-prop
Styled Components polymorphic `as` prop is really useful in certain cases (converting a `Button` component from a `<button>` to an `<a>` for example). Developers who are familiar with the library will be confused why the `as` prop doesn't work. It makes sense that we need to be careful with what tags we allow, but we can easily verify against our `ApprovedTagsSimple` list and remove the attribute if the tag isn't allowed.
=> Safely support styled-components "as" prop

webpack.config.js
This allows develop VM locally.
1) Execute `yarn link` in the VM repo
2) Execute `yarn link "near-social-vm"` in this repo.
=> Add alias for react and react-dom

package.json, src/App.js, src/data/web3.js, src/index.css, webpack.config.js, yarn.lock
The following change enables `Ethers` and `ethers` using `ethers.js` from the VM.
To enable Web3 in the VM, the gateway should inject Web3 provider in the specific react context `EthersProviderContext` given from the VM.
Currently the implementation depends on the Web3Onboard as a wallet selector. 
See https://github.com/NearSocial/VM/pull/44
=> Enable Ethers.js 

src/data/web3.js
- Update new EVM chains to the list of chains for Web3Onboard.
- Expose `setChain` to the `VM` through `EthersProviderContext`
=> Update Web3 chains list and expose setChain

functions/[[accountId]]/widget/[[index]].js, functions/common.js, functions/magic/img/account/[index].js, functions/magic/img/nft/[[index]].js, yarn.lock
Expose 2 endpoints:
- `/magic/img/account/[accountId]` to resolve image of the account to the URL
- `/magic/img/nft/[contractId]/[tokenId]` to resolve the image of the NFT to the URL
=> Add account image endpoint

package.json, src/components/Editor/FileTab.js, src/pages/EditorPage.js
Adds a toggle button the Editor. When it's ON, the preview uses uncommitted code from all opened files. It allows to develop widgets that require complicated props or depend on other widgets
=> feat: Add multi-file preview

package.json, src/App.js, src/components/icons/QR.js, src/components/navigation/MobileQRModal.js, src/components/navigation/desktop/UserDropdown.js, src/data/widgets.js, src/pages/SignInPage.js, yarn.lock
Ability to display a QR code on desktop version with the local secret key. When the QR is scanned on mobile, it redirects to a sign in prompt. No full access key required.
Demo showing the QR code
https://github.com/NearSocial/viewer/assets/470453/36d82cba-a516-4594-a30b-07538e2d234c
Sign in flow
https://github.com/NearSocial/viewer/assets/470453/b7bc09e4-6bfa-49c1-9e31-8b7ed0e4ad86
=> QR Sign In for Mobile

functions/common.js, functions/magic/img/nft/[[index]].js
Magic function to return an image url for the NFT collection icon
=> Magic: return NFT collection icon

src/pages/EditorPage.js, src/pages/ViewPage.js
It would allow main widget to overflow into the menu as well to the sides
=> Remove overflow on view page

README.md, public/index.html, src/App.scss, src/components/Editor/FileTab.js, src/components/Editor/OpenModal.js, src/index.css, src/pages/EditorPage.js
Closes: https://github.com/near/near-discovery/issues/852 
Here are some test cases for anyone interested in testing the desired behavior.
1. From the near.social hamburger menu click fork 
2. The IDE should open with the forked component code in focus, there should be a default tab visible.
3. When switching between tabs the editor should display the code associated with the selected tab
4. When "saving"(equivalenet to near.org publish) the user should be prompted with a "Saving Data" modal. Ensure that the metadata for the fork_of property is there if the current component is in fact a fork and not there if the component is not a fork.
5. Ensure that if there are multiple components in the editor that switching between the tabs results in the component data in the active tab of the …
=> feat: add fork data to metadata in the editor
