src/vm/vm.js
The functions are now real functions. It means all props that takes them are now working. Hello onClick, onChange
=> Improve functions

src/vm/vm.js
This enables ability to handle input events. E.g. 
```jsx
State.init({ accountId: "test" });
const change = (e) => {
State.update({ accountId: e.target.value.toLowerCase() });
};
return (
<div>
<input type="text" value={state.accountId || ""} onChange={change} />
{JSON.stringify(state)}
</div>
);
```
=> Expose Events to local functions

package.json, src/App.js, src/components/Markdown.js, src/components/Widget/Widget.js, src/data/near.js, src/pages/EditorPage.js, src/pages/ViewPage.js, src/vm/vm.js, webpack.config.js, yarn.lock
Introducing `Markdown` and React Framents.
Markdown example:
```jsx
const src = props.src ?? "mob.near/widget/WidgetSource";
const code = Social.get(src);
const text = `
\`\`\`jsx
${code}
\`\`\`
`;
return <Markdown text={text} />;
```
=> Ship markdown, react fragments, widget source

package.json, src/vm/vm.js, yarn.lock
Add InifiteScroll react component based on https://www.npmjs.com/package/react-infinite-scroller
Widget example:
```jsx
const accountId = props.accountId ?? "*";
const data = Social.keys(`${accountId}/post/meme`, "final", {
return_type: "History",
});
if (!data) {
return "Loading";
}
const processData = (data) => {
const accounts = Object.entries(data);
const allMemes = accounts
.map((account) => {
const accountId = account[0];
const blockHeights = account[1].post.meme;
return blockHeights.map((blockHeight) => ({
accountId,
blockHeight,
}));
})
.flat();
allMemes.sort((a, b) => b.blockHeight - a.blockHeight);
return allMemes;
};
const memeToWidget = (a) => (
<div key={JSON.stringify(a)} style={{ minHeight: "200px" }}>
<a
className="text-decoration-none" …
```
=> Add InfiniteScroll

src/components/Widget/Widget.js, src/data/cache.js, src/data/commitData.js, src/data/near.js, src/pages/EditorPage.js, src/vm/vm.js
This allows to retrieve the block at a given finality or blockHeight.
```jsx
const block = Near.block();
return block.header.height;
```
=> Introduce Near.block

package.json, src/data/utils.js, src/vm/vm.js, yarn.lock
Add `Typeahead` component based on https://github.com/ericgio/react-bootstrap-typeahead/tree/main/docs
Demos: https://ericgio.github.io/react-bootstrap-typeahead/
Widget demo:
```jsx
const widgets = Social.keys("mob.near/widget/*")["mob.near"].widget;
const options = Object.keys(widgets || {});
initState({
multiSelections: [],
});
const setMultiSelections = (multiSelections) => {
State.update({ multiSelections });
};
return (
<div>
<div className="p-1">
<Typeahead
id="widget selector"
multiple
onChange={setMultiSelections}
options={options}
placeholder="Choose widgets"
selected={state.multiSelections}
positionFixed
allowNew
/>
</div>
<div>
<pre>{JSON.stringify(state)}</pre>
</div>
</div>
);
```
=> Add Typeahead

src/components/Commit.js, src/data/near.js, src/pages/EditorPage.js, src/vm/vm.js
Editor now supports adding Metadata to the widget
=> Integrating Widget's Metadata

package.json, src/App.js, src/components/Widget/Widget.js, src/data/near.js, yarn.lock
- Updates widgets if the accountId has changed.
=> Integrating meteor wallet. Fixing wallet selector

package.json, src/components/ConfirmTransaction.js, src/vm/vm.js, yarn.lock
Introduce `styled` components from https://styled-components.com/
Example:
```jsx
// The Button from the last section without the interpolations
const Button = styled.button`
color: palevioletred;
font-size: 1em;
margin: 1em;
padding: 0.25em 1em;
border: 2px solid palevioletred;
border-radius: 3px;
`;
// A new component based on Button, but with some override styles
const TomatoButton = styled(Button)`
color: tomato;
border-color: tomato;
`;
return (
<div>
<Button>Normal Button</Button>
<TomatoButton>Tomato Button</TomatoButton>
</div>
);
```
=> Introduce styled components

src/components/Widget/Widget.js, src/pages/EditorPage.js, src/vm/vm.js
Test case:
```jsx
const {
a,
b: [b, ...c],
...d
} = {
a: "a",
b: ["b1", "b2", "b3"],
c: "c",
d: "d",
};
return {
a,
b,
c,
d,
t1: [a, b, ...c],
t2: { a, b, ...d },
};
```
=> Improve VM. Support RestElement, SpreadElement

src/App.scss, src/data/utils.js, src/vm/vm.js
- ChainExpression to support expressions like "a?.b".
- Introduce `Math`, `Big` from `big.js`, `Number`. Expose more `Date` methods.
- Refactored `callFunction` to support `optional` 
- `new` is now attempting to call the method. It doesn't check if the method is a constructor.
- Support `delete`
=> Add ChainExpression, Math, big.js, Number

src/components/Editor/OpenModal.js, src/components/Editor/RenameModal.js, src/data/cache.js, src/pages/EditorPage.js
The new editor supports multiple opened files.
It let you switch between them and rename them.
Note, it still doesn't let you save all of them or apply changed code for multiple widgets at once.
=> Introduce new editor

src/vm/vm.js
Example:
```jsx
try {
console.log("try");
throw { a: "Rekt" };
} catch (e) {
console.log("catch", e);
} finally {
console.log("final");
}
console.log("exit");
return "ok";
```
=> Add try-catch-finally and throw

package.json, src/data/utils.js, src/index.js, src/vm/vm.js, yarn.lock
Exposes new objects and libraries:
- `nacl` - imports everything from `tweetnacl` npm
- `elliptic` - imports everything from `elliptic`
- `BN` - BN object from bn.js
- `Uint8Array` - exposes `Uint8Array`
Buffer and Uint8Array are supported by `deepCopy`
Example:
```jsx
const box = nacl.box;
const newNonce = () => nacl.randomBytes(box.nonceLength);
const generateKeyPair = () => box.keyPair();
const json = {
a: "test",
};
const encrypt = (secretOrSharedKey, json, key) => {
const nonce = newNonce();
const messageUint8 = new Uint8Array(
Buffer.from(JSON.stringify(json), "utf-8")
);
const encrypted = key
? box(messageUint8, nonce, key, secretOrSharedKey)
: box.after(messageUint8, nonce, secretOrSharedKey);
const fullMessage = new Uint8Array(nonce.length + encrypted.length); …
```
=> 0.2.0: Add BN, elliptic and nacl libs

src/vm/vm.js
Introduce `clipboard.writeText` to copy given text to the clipboard.
The event requires for the page to be in transient state (explicit user's click).
But also for extra safety, the VM now has `isTrusted` as part of the stack. This allows, to verify if the action was part of the stack originating from the `isTrusted` user's event.
Code example:
```jsx
return (
<div>
<div>
<button
onClick={() => {
clipboard.writeText("HelloWorld!");
}}
>
Copy "HelloWorld!" to clipboard
</button>
</div>
<textarea className="form-control mt-2" placeholder="Test pasting here" />
</div>
);
```
=> Add clipboard.writeText

src/data/near.js, src/pages/EditorPage.js
Introduce component search to the editor that let you quickly search for the components to embed or fork.
=> Add component search

src/vm/vm.js
Fixes: #89 
```jsx
const array1 = ["a", "b", "c"];
let element = { a: 3 };
for (element.a of array1) {
console.log(element);
}
// expected output: "a"
// expected output: "b"
// expected output: "c"
```
=> Add ForOfStatement

src/data/cache.js, src/data/utils.js, src/vm/vm.js
Changes:
- Expose `Files` component which works like input files and allows drag and drop. It's a dependency from `IpfsImageUpload` component.
- Add `File` and `Blob` to deepCopy, so functions can accept them.
- Add support for `blob` response type for `fetch` and `asyncFetch` to fetch binary data. Not needed for this implementation.
Example using `Files` component to replicate `IpfsImageUpload` component
```jsx
initState({
img: null,
});
const ipfsUrl = (cid) => `https://ipfs.near.social/ipfs/${cid}`;
const filesOnChange = (files) => {
if (files?.length > 0) {
State.update({
img: {
uploading: true,
cid: null,
},
});
const body = files[0];
asyncFetch("https://ipfs.near.social/add", {
method: "POST",
headers: {
Accept: "application/json",
},
body,
}).then((res) => {
const cid = …
```
=> Expose Files component, add File/Blob to deepCopy, support blob in fetch

src/components/navigation/desktop/UserDropdown.js, src/components/navigation/mobile/Menu.js
=> fix: Fix desktop dropdown icon width issue

src/components/navigation/desktop/UserDropdown.js, src/components/navigation/mobile/Menu.js
Adding prefix for profile navigation
=> Fix profile link

src/components/remark/mentions.js
=> Fix Mentions Regex

src/vm/vm.js
Example:
```jsx
function a() {
console.log("hi");
}
return a.toString();
```
=> Prevent functions from being dereferenced

src/data/cache.js
When page is opened for a while the content becomes stale and is never updated. This change makes the cache expire after 5 minutes, so a request will be made again.
=> Refresh in-memory cache every 5 minutes

src/components/Widget/Widget.js
Expose `context.widgetSrc` the current `src` from the `Widget`.
```jsx
return context.widgetSrc;
```
=> Expose context.widgetSrc

src/vm/vm.js
Enable `a` tag for styled components
=> Fix styled.a

src/vm/vm.js
Because the VM runs on every state update, all non-cached styled components are recreated. This resets the class of the component. When this happens all inputs are becoming slightly different components and loses cursor position.
Demo with issues before this fix:
```jsx
initState({ a: 1 });
const A = styled.div`
background: pink;
`;
console.log(state);
return (
<A>
Hello World <input type="text" value={state.a} />
</A>
);
```
=> Cache styled components

src/data/near.js
Switch routing of view calls from archival NEAR RPC to the near social RPC server
=> Switch non-optimistic calls to API server

src/vm/vm.js
```jsx
for (let i = 0; i < 10; ++i) {
if (i % 2) {
continue;
}
console.log(i);
}
```
=> Add ContinueStatement

src/App.js, src/components/navigation/desktop/DesktopNavigation.js, src/components/navigation/mobile/Menu.js
Update navigation docs link to https://social.near-docs.io/
=> Update documentation link

package.json, src/components/Editor/FileTab.js, src/pages/EditorPage.js
- Add an asterisk to the Editor tabs for components that are different from the chain version.
- Add "Close unchanged" button.
=> Add unsaved and Close unchanged to the Editor

package.json, src/App.js, yarn.lock
Related to: https://github.com/NearSocial/VM/pull/55
=> Add typeahead CSS imports

package.json, src/App.js, yarn.lock
=> Add Link element

src/App.js, src/hooks/useQuery.js
fixes #175
also fixes: https://github.com/near/neardevhub-widgets/issues/199
=> fix: keep query string params from wallet callback

.gitignore, config/webpack.development.js, package.json, public/index.html, src/App.js, src/hooks/useHashRouterLegacy.js, src/hooks/useQuery.js, src/pages/EditorPage.js, src/pages/EmbedPage.js, src/pages/ViewPage.js, webpack.config.js
Switching from HashRouter to BrowserRouter.
This will switch urls from like https://near.social/#/mob.near/widget/Welcome to https://near.social/mob.near/widget/Welcome and automatically redirect.
=> Drop hash router

functions/[[accountId]]/widget/[[index]].js, functions/common.js, functions/sitemap/index.js, functions/sitemap/posts/[index].js, functions/sitemap/posts/index.js, functions/sitemap/profiles/index.js, functions/sitemap/sources/index.js, functions/sitemap/widgets/index.js, public/index.html, public/robots.txt
Generate sitemaps with functions
=> Add sitemap and sources preview

package.json, src/App.js, yarn.lock
Set default finality to `final` to route everything through the API server instead of the RPC
=> Setup default finality to `final`

package.json, yarn.lock
=> VM #no-stale

package.json, src/pages/EditorPage.js, yarn.lock
Bump VM to 2.4.2
Enable suggestions in the online Editor using `near-social-vm-types`.
=> Enable suggestions in the Editor

src/App.scss
To avoid content jumping, enable scroll by default
=> Enable scroll-y on body

package.json, src/components/navigation/desktop/DesktopNavigation.js, src/components/navigation/mobile/Navigation.js
Click on logo also scrolls to the top of the page
=> Scroll to top

src/components/navigation/desktop/DevActionsDropdown.js, src/pages/EditorPage.js
Slight redesign of near.social Editor. More space, adjust labels, less color
=> Improve UI in the editor

src/components/navigation/StarButton.js, src/components/navigation/desktop/DesktopNavigation.js, src/components/navigation/desktop/DevActionsDropdown.js, src/components/navigation/mobile/Navigation.js, src/data/widgets.js
=> Ability to star current application

src/pages/ViewPage.js
- Ability to inject forcedWidget
- Ability to inject props
=> Inject props and forced widget

src/hooks/useHashRouterLegacy.js
Allows components to use regular hash fragments for links within a pagge
=> Update how hash router works

package.json, src/App.js
Add option into `InjectedConfig` to skip all modal confirmations
=> Bypass modals

package.json, src/App.js, src/data/widgets.js, src/pages/SignInPage.js, yarn.lock
- Remove NETH
- Update Bitte to use `lak`
- Add Near Mobile Wallet
- Update wallet order
=> Update wallet selector options
